### ISSUE TITLE
Function to record

### ISSUE THREAD

**Issue by asyrafzlkln96** [ashwan1/django-deepspeech-server#22]
Hi, I want to ask, where is the function of record for the voice?
When we access the web browser, there is two options, 
whether to record your own voice or to upload the 16kHz audio file right?
So i need to know is the voice we record is converted to 16k?
And where is the record function located?

Thank you.
ASyraf

**Comment by ashwan1** [comment]
Yes, voice is converted to 16k sample rate. Functions are in audioRecorder.js and audioRecorderWorker.js files.
