### ISSUE TITLE
Size of wav file

### ISSUE THREAD

**Issue by gr8nishan** [ashwan1/django-deepspeech-server#7]
What is the max size of the audio file that we can give as input and how to increase that size.

**Comment by ashwan1** [comment]
Currently there is no validation for audio file size and type. I was planning to add that this weekend.

**Comment by Hafsa26** [comment]
Is wav_file size is in seconds ?
Kindly Help. Thank you so much!

**Comment by ashwan1** [comment]
@Hafsa26 yes, audiofilelength is in seconds

**Comment by Hafsa26** [comment]
Hi.
Ashwan, Its in bytes. I got it.
Thank you for replying.
